CREATE SCHEMA PROYECTO_FINAL_DATABASE;

USE PROYECTO_FINAL_DATABASE;

-- Tabla Dirección
CREATE TABLE DIRECCION (
    ID_DIRECCION INT AUTO_INCREMENT PRIMARY KEY,
    PAIS VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    CIUDAD VARCHAR(100),
    BARRIO VARCHAR(100),
    NOMENCLATURA VARCHAR(200),
    DESCRIPCION VARCHAR(200)
);

-- Tabla Cliente
CREATE TABLE CLIENTE (
    NUM_IDENTIFICACION BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    GENERO ENUM('M', 'F') NOT NULL,
    EDAD INT NOT NULL,
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100) UNIQUE,
    OCUPACION VARCHAR(100),
    INGRESO_MENSUAL DECIMAL(10, 2),
    EGRESO_MENSUAL DECIMAL(10, 2),
    SCORE INT,
    ID_DIRECCION INT,
    FECHA_REGISTRO DATE NOT NULL DEFAULT (CURRENT_DATE),
    ESTADO ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);

-- Tabla Credenciales
CREATE TABLE CREDENCIALES(
    NUM_IDENTIFICACION BIGINT UNIQUE NOT NULL,
    USUARIO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASEÑA VARCHAR(100) NOT NULL,
    ULTIMA_CONEXION DATETIME NOT NULL,
    FOREIGN KEY (NUM_IDENTIFICACION) REFERENCES CLIENTE(NUM_IDENTIFICACION)
);

-- Tabla Cuentas_Bancarias
CREATE TABLE CUENTAS_BANCARIAS (
    ID_CUENTA INT PRIMARY KEY,
    TIPO_CUENTA ENUM('Ahorros', 'Corriente') NOT NULL,
    TASA_RENTABILIDAD DECIMAL(5, 2) NOT NULL,
    INTERES_SOBREGIRO DECIMAL(5, 2),
    DESCRIPCION TEXT,
    CUOTA_MANEJO DECIMAL(10, 2) NOT NULL
);

-- Tabla Cliente_Cuenta
CREATE TABLE CLIENTE_CUENTA (
    NUMERO_OBLIGACION INT PRIMARY KEY,
    ID_CUENTA INT,
    NUM_IDENTIFICACION BIGINT,
    SALDO DECIMAL(15, 2) NOT NULL,
    CUPO_SOBREGIRO DECIMAL(15, 2),
    FECHA_APERTURA DATE NOT NULL DEFAULT (CURRENT_DATE),
    TARJETA_FISICA BOOLEAN NOT NULL DEFAULT FALSE,
    TARJETA_VIRTUAL BOOLEAN NOT NULL DEFAULT FALSE,
    FRANQUICIA VARCHAR(100),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTAS_BANCARIAS(ID_CUENTA),
    FOREIGN KEY (NUM_IDENTIFICACION) REFERENCES CLIENTE(NUM_IDENTIFICACION)
);

-- Tabla Tarjetas_Credito
CREATE TABLE TARJETAS_CREDITO (
    ID_TARJETA_CREDITO INT PRIMARY KEY,
    FRANQUICIA ENUM('Visa', 'MasterCard') NOT NULL,
    DESCRIPCION TEXT,
    TASA_INTERES_EFECTIVO_ANUAL DECIMAL(5, 2) NOT NULL,
    TASA_INTERES_POR_MORA DECIMAL(5, 2) NOT NULL
);

-- Tabla Cliente_Tarjeta_Credito
CREATE TABLE CLIENTE_TARJETA_CREDITO (
    NUMERO_OBLIGACION INT PRIMARY KEY,
    ID_TARJETA_CREDITO INT,
    NUM_IDENTIFICACION BIGINT,
    CUPO DECIMAL(15, 2) NOT NULL,
    CUPO_DISPONIBLE DECIMAL(15, 2) NOT NULL,
    FECHA_APERTURA DATE NOT NULL DEFAULT (CURRENT_DATE),
    CUOTAS INT NOT NULL,
    FECHA_CORTE DATE NOT NULL,
    FECHA_PAGO DATE NOT NULL,
	FECHA_APROBACION DATE NOT NULL DEFAULT (CURRENT_DATE),
    ESTADO ENUM('Activo','En cartera','Bloqueada','Cancelada') NOT NULL DEFAULT 'Activo',
    FOREIGN KEY (ID_TARJETA_CREDITO) REFERENCES TARJETAS_CREDITO(ID_TARJETA_CREDITO),
    FOREIGN KEY (NUM_IDENTIFICACION) REFERENCES CLIENTE(NUM_IDENTIFICACION)
);

-- Tabla Cartera
CREATE TABLE CARTERA (
    ID_CARTERA INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_OBLIGACION INT,
    DIAS_MORA INT NOT NULL,
    MONTO_ADEUDADO DECIMAL(15, 2) NOT NULL,
    INTERES_MORA DECIMAL(15, 2) NOT NULL,
    PROCESO_RECUPERACION TEXT,
    FECHA_INICIO_MORA DATE NOT NULL DEFAULT (CURRENT_DATE),
    FOREIGN KEY (NUMERO_OBLIGACION) REFERENCES CLIENTE_TARJETA_CREDITO(NUMERO_OBLIGACION)
);

-- Tabla Transacciones_Cuentas_Bancarias
CREATE TABLE TRANSACCIONES_CUENTAS_BANCARIAS (
    ID_TRANSACCION INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_TRANSACCION ENUM ('Transferencia','Retiro','Recepción') NOT NULL,
    NUMERO_OBLIGACION INT,
    NUMERO_DESTINO INT,
    MONTO DECIMAL(15, 2) NOT NULL,
    FECHA_TRANSACCION DATE NOT NULL DEFAULT (CURRENT_DATE),
    DESCRIPCION TEXT,
    FOREIGN KEY (NUMERO_OBLIGACION) REFERENCES CLIENTE_CUENTA(NUMERO_OBLIGACION),
    FOREIGN KEY (NUMERO_DESTINO) REFERENCES CLIENTE_CUENTA(NUMERO_OBLIGACION)
);

-- Tabla Transacciones_Cuentas_Tarjeta_Credito
CREATE TABLE TRANSACCIONES_CUENTAS_TARJETA_CREDITO (
    ID_TRANSACCION INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_TRANSACCION ENUM ('Pago', 'Avance', 'Abono') NOT NULL,
    NUMERO_OBLIGACION INT,
    MONTO DECIMAL(15, 2) NOT NULL,
    FECHA_TRANSACCION DATE NOT NULL DEFAULT (CURRENT_DATE),
    DESCRIPCION TEXT,
    FOREIGN KEY (NUMERO_OBLIGACION) REFERENCES CLIENTE_TARJETA_CREDITO(NUMERO_OBLIGACION)
);
